### ISSUE TITLE
Please can you make an example and add the example to the README

### ISSUE THREAD

**Issue by clyde00r** [AlphaMoonbaseBerlin/bananaMash#1]
It's not straight forward to understand how this works, i.e:

1. How do you bind events to the states?
2. How do you change the states programmatically
3. How does the state system work?
4. What is a standard workflow with and without events listener to make your approach work in practice?
5. Can you give multiple practical examples in your github README.

Thank you in advance.

**Comment by AlphaMoonbaseBerlin** [comment]
Hi @Thisplacecontains 
Thanks for your feedback.
I will see that I add better documentation for this tool in the future, but keep in mind that this is an internal tool I offer usage for free.

**Comment by AlphaMoonbaseBerlin** [comment]
@Thisplacecontains 
Check out this video and the V2 branch, should give you some examples.
https://www.youtube.com/watch?v=H-E8dfufwHQ
