### ISSUE TITLE
UI not updating in demo.toe

### ISSUE THREAD

**Issue by delray** [AlphaMoonbaseBerlin/bananaMash#6]
Hi,
I am looking into state machines in TD and ran across your implementation - it looks really interesting and seems to mostly work on my side, but when I load your demo.toe, the UI in the banamash comp is exactly the same as the default setup. It just shows "initstate, A, D, C, and momentary" nodes in the graph.  However, I do see the states listed in the 'bananmash_states comp (initstate, Idle, Enough, goodbye)

![image](https://github.com/user-attachments/assets/f5cf875b-9f19-4743-b856-d78a9ed4f961)

Is there a way to force an update of the UI that I am missing somewhere?

thanks for your help and what looks to be a really promising contribution to the community!

**Comment by AlphaMoonbaseBerlin** [comment]
Hey @delray 
It was missing the refferences to the correct COMPS. 
The Comp has three üparameters pointing to external data repositories. It was still pointing at the internal one.
I fixed that with my latest commit:
![grafik](https://github.com/user-attachments/assets/e1610994-2a3b-454b-a753-fa273860299a)

**Comment by delray** [comment]
ty,
i was just writing to you that I found it...thanks for the quick response!

**Comment by AlphaMoonbaseBerlin** [comment]
Sweet.
Let me know if you have any feedback.
