### ISSUE TITLE
Dbl Click not consistent to create new state

### ISSUE THREAD

**Issue by delray** [AlphaMoonbaseBerlin/bananaMash#7]
Basically as it says above,  the double clicking to create a new state seems very hit and miss on my side. It works maybe one out of ten/fifteen times or even less.  I have been working around it by just duplicating states in the bananamash_states COMP and going from there.  I'm on TD 2023.11880 fwiw...

**Comment by AlphaMoonbaseBerlin** [comment]
Thanks for the feedback @delray 
Hmmm, might be something that I need to address in the RIF. 
For testing you can go in to
**bananaMash/UI** and adjust the Multitap-Timing of the interactionEngine-Comp.
I set it to a value I can hit consistantly, but I see that with a trackpad for example it is harder to hit. Mayb try 160.
Just be aware that this influences also the selection-speed of other elements, so it is hard to find a nice balance between doubletap time and selection-speed.
But it might also be something in the RIF that is resulting in this behaviour as 90 should actualy be able to be hit nicely.

**Comment by AlphaMoonbaseBerlin** [comment]
@delray 
Can you try with the latest commit? I changed the way I handle the click a little bit which should be better
+You can also set the BANANAMASH_UI_TAPTIMING ENV-variable to a value higher then 160 if it still does not work.

**Comment by delray** [comment]
Big apologies for the long delay in getting back to you, I got pulled into another project, but things are looking very smooth now here and i'm able to dblClick and create new nodes. It also seems easy to click on connections too.  thanks!
